### ISSUE TITLE
JET analysis will produce code different from what Julia's native compiler produces.

### ISSUE THREAD

**Issue by jakobnissen** [aviatesk/JET.jl#118]
This is a little disturbing, but I'm able to reproduce it 100% reliably. In the two examples below, the *exact same* function `f` is shown to compile differently depending on whether JET is used or not:

MWE
```julia
using ErrorTypes # commit 59441d34530aa4fcd366885575847f3b15ca5902
# using JET # commit 37151f880ab067ac2ddd6d1e2338c3b8e14c4cdc
safediv(a, b)::Option{Float64} = iszero(b) ? none : some(a/b)
f(x)::Option{Float64} = some(@? safediv(1, x))
# @report_call f(1)
@code_native f(1)
```

Try running the above and look at the native code, and then run it again without the two lines commented out.

**Comment by aviatesk** [comment]
Good catch. This is expected.

JET's analysis [disables inlining](https://github.com/aviatesk/JET.jl/blob/37151f880ab067ac2ddd6d1e2338c3b8e14c4cdc/src/abstractinterpreterinterface.jl#L150) for reasons, and so `@report_call` or such will produce really different code from Julia's native compiler.  So if you will actually run your code, it's better not to do JET analysis in the same session.

In my plan, JET will offer a proper UI to show JET analysis's result to users, whose process is not supposed to interact with actual user's runtime. Then `@report_call` will just be an entrypoint of JET's testing, basically, and so won't interact with users runtime.
