### ISSUE TITLE
Errors on function definition using a global variable

### ISSUE THREAD

**Issue by markhalonen** [aviatesk/JET.jl#142]
I'm a Julia noob coming from the statically checked TypeScript world, so don't assume competence here.

I have this code in `main.jl`:
```julia
Circle = @NamedTuple begin
    radius::Float64
end

function area(c::Circle)
    pi * c.radius^2
end

area(Circle(2))
```

When I `report_and_watch_file("main.jl"; annotate_types = true)` I get 
```
[toplevel-info] entered into src/main.jl
[toplevel-info]  exited from src/main.jl (took 0.008 sec)
═════ 1 toplevel error found ═════
┌ @ src/main.jl:31 
│ ArgumentError: invalid type for argument c in method definition for area at src/main.jl:31
└──────────────────
```

**Comment by markhalonen** [comment]
Ok, so @krrutkow's suggestion is to add `const`:
```julia
const Circle = @NamedTuple begin
    radius::Float64
end

function area(c::Circle)
    pi * c.radius^2
end

area(Circle(2))
``` 
and that works. Close the issue if you see fit!

**Comment by aviatesk** [comment]
Yes, a top-level definition (like function definition) with accessing to global variables is really troublesome for JET.jl.
#143 will fix this kind of case, though.

As a side note, you can have a configuration file like below and the specified pattern will be concretized as actual execution,
and you can analyze your file w/o problem even if you don't declare `Circle` as `const` (even w/o #143)
> .JET.toml
```toml
concretization_patterns = ["Circle = x_"]
```
(see https://aviatesk.github.io/JET.jl/dev/config/#JET.ToplevelConfig if interested)
