### ISSUE TITLE
how big is the difference in analysis quality between julia 1.6 and the latest nightly?

### ISSUE THREAD

**Issue by alok** [aviatesk/JET.jl#158]
as far as jet.jl goes

**Comment by aviatesk** [comment]
There have been many improvements:
- inference improvements:
  * https://github.com/JuliaLang/julia/pull/38905
  * https://github.com/JuliaLang/julia/pull/39305
  * and many other PRs ...   
- inferrability improvements in `Base`
  * e.g. https://github.com/JuliaLang/julia/pull/40463

Both changes have impacts on JET's analysis result.
