### ISSUE TITLE
One-line code fails type checking when using Base.split()

### ISSUE THREAD

**Issue by zengmao** [aviatesk/JET.jl#172]
The one-line code

    split("1,2,3", ',')

when saved to a file, fails type checking:

    julia> using JET
    
    julia> report_file("oneline.jl")
    [toplevel-info] virtualized the context of Main (took 0.035 sec)
    [toplevel-info] entered into oneline.jl
    [toplevel-info]  exited from oneline.jl (took 2.966 sec)
    ═════ 2 possible errors found ═════
    ┌ @ oneline.jl:1 split("1,2,3", ',')
    │┌ @ strings/util.jl:411 Base.#split#375(0, true, #self#, str, splitter)
    ││┌ @ strings/util.jl:411 Base._split(str, Base.isequal(splitter), limit, keepempty, _7)
    │││┌ @ strings/util.jl:421 Base.first(r)
    ││││┌ @ abstractarray.jl:386 Base.iterate(itr)
    │││││ no matching method found for call signature: Base.iterate(itr::Nothing)
    ││││└────────────────────────
    │││┌ @ strings/util.jl:421 Base.last(r)
    ││││┌ @ abstractarray.jl:437 Base.lastindex(a)
    │││││ no matching method found for call signature: Base.lastindex(a::Nothing)
    ││││└────────────────────────
    (included_files = Set(["oneline.jl"]), any_reported = true)

**Comment by aviatesk** [comment]
That's because of type instability in Base, and already fixed on v1.7.
