### ISSUE TITLE
Error with nested map

### ISSUE THREAD

**Issue by etienneINSA** [aviatesk/JET.jl#173]
The following code
```julia
map(x->x, map(x->x, []) )
```
result in this error
``` julia
TypeError: in new, expected UnionAll, got Type{Tuple}
```
I didn't manage to make it smaller, I have no clue on what's going on.

**Comment by aviatesk** [comment]
Thanks for your report ! Will dig into this over the weekend.

**Comment by aviatesk** [comment]
Hm, I couldn't repro this.
What's the versions of your JET and julia ?

**Comment by etienneINSA** [comment]
Ah, it's nastier than what I thought, it only works when I have one of my personal package loaded, I will investigate this tonight and give you a cleaner MWE.

**Comment by etienneINSA** [comment]
Ok, the problem is not that much on my package, but on the JuMP package. 
Executing `using JuMP` before reporting the file should be sufficient to reproduce it, but it is probably possible to dig down a bit more, I will try to do what I can...

**Comment by aviatesk** [comment]
Okay, this is the issue of Julia:
- https://github.com/JuliaLang/julia/issues/40054
- https://github.com/JuliaLang/julia/issues/35661

This doesn't happen on the nightly Julia, though.
