### ISSUE TITLE
Error when a struct contains a field of type Vector{Number}

### ISSUE THREAD

**Issue by zengmao** [aviatesk/JET.jl#178]
The file is as follows

    # filename: struct_vector.jl
    struct MyVector
        data::Vector{Number}
    end

Here's the error, with Julia 1.6.0 and github version of JET.jl:

    julia> report_file("struct_vector.jl", analyze_from_definitions=true);
    [toplevel-info] virtualized the context of Main (took 0.029 sec)
    [toplevel-info] entered into struct_vector.jl
    [toplevel-info]  exited from struct_vector.jl (took 2.113 sec)
    [toplevel-info] analyzing from top-level definitions ... 2/2
    ═════ 1 possible error found ═════
    ┌ @ struct_vector.jl:2 Base.convert(Core.fieldtype(MyVector, 1), data)
    │┌ @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/factorization.jl:58 _(f)
    ││ no matching method found for call signature: _::Type{Vector{Number}}(f::LinearAlgebra.Factorization)

**Comment by aviatesk** [comment]
dup of #145.
