### ISSUE TITLE
`TypeError` when running `JET.report_package`

### ISSUE THREAD

**Issue by adomasbaliuka** [aviatesk/JET.jl#226]
# Error description
First time trying out JET.jl and trying to run `report_package` on a custom package, I got the following error:

> ERROR: TypeError: in typeassert, expected Vector{Any}, got a value of type Nothing

Stacktrace is attached: [JET_stacktrace.txt](https://github.com/aviatesk/JET.jl/files/6876741/JET_stacktrace.txt).

If any further information would help, let me know. Thanks!

# System information

Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
[JET_stacktrace.txt](https://github.com/aviatesk/JET.jl/files/6876740/JET_stacktrace.txt)

  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 8

JET v0.4.5

**Comment by goerch** [comment]
This is not reproducible for me.
