### ISSUE TITLE
ERROR: cannot assign a value to variable Main.Struct from module ##JETVirtualModule#259

### ISSUE THREAD

**Issue by bardo84** [aviatesk/JET.jl#236]
julia> report_and_watch_file("serialize_5.jl"; annotate_types = true)
[toplevel-info] virtualized the context of Main (took 0.007 sec)
[toplevel-info] entered into serialize_5.jl
ERROR: cannot assign a value to variable Main.Struct from module ##JETVirtualModule#259
Stacktrace:
 [1] top-level scope
   @ none:1

[serialize_5.jl](https://gist.github.com/bardo84/b914b876cc80bc9a89ee982594293ef6)

**Comment by aviatesk** [comment]
I could analyzer your file with `report_file("serialize_5.jl"; concretize_patterns = [:(Writable = x_)])`.

**Comment by bardo84** [comment]
Thanks a lot for your response!

>report_file("serialize_5.jl"; concretize_patterns = [:(Writable = x_)])
Where does this call come from, did I oversee something in the notes?

How to interpret this error/warning?
>@ _serialize5.jl:12  # blanc line
>...
>MethodError: no method matching zero(::Type{Any})

**Comment by aviatesk** [comment]
Literally, there is no method for `zero(::Type{Any}` :p 
```julia
julia> zero(Any)
ERROR: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T at missing.jl:105
  zero(::Union{Type{P}, P}) where P<:Dates.Period at /Users/aviatesk/julia/julia/stdlib/Dates/src/periods.jl:53
  zero(::AbstractIrrational) at irrationals.jl:150
  ...
Stacktrace:
 [1] zero(#unused#::Type{Any})
   @ Base ./missing.jl:106
 [2] top-level scope
   @ REPL[1]:1

julia> sum([])
ERROR: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T at missing.jl:105
  zero(::Union{Type{P}, P}) where P<:Dates.Period at /Users/aviatesk/julia/julia/stdlib/Dates/src/periods.jl:53
  zero(::AbstractIrrational) at irrationals.jl:150
  ...
Stacktrace:
  [1] zero(#unused#::Type{Any})
    @ Base ./missing.jl:106
  [2] reduce_empty(#unused#::typeof(+), #unused#::Type{Any})
    @ Base ./reduce.jl:325
  [3] reduce_empty(#unused#::typeof(Base.add_sum), #unused#::Type{Any})
    @ Base ./reduce.jl:334
  [4] mapreduce_empty(#unused#::typeof(identity), op::Function, T::Type)
    @ Base ./reduce.jl:354
  [5] reduce_empty(op::Base.MappingRF{typeof(identity), typeof(Base.add_sum)}, #unused#::Type{Any})
    @ Base ./reduce.jl:343
  [6] reduce_empty_iter
    @ ./reduce.jl:366 [inlined]
  [7] mapreduce_empty_iter(f::Function, op::Function, itr::Vector{Any}, ItrEltype::Base.HasEltype)
    @ Base ./reduce.jl:362
  [8] _mapreduce(f::typeof(identity), op::typeof(Base.add_sum), #unused#::IndexLinear, A::Vector{Any})
    @ Base ./reduce.jl:414
  [9] _mapreduce_dim
    @ ./reducedim.jl:330 [inlined]
 [10] #mapreduce#731
    @ ./reducedim.jl:322 [inlined]
 [11] mapreduce
    @ ./reducedim.jl:322 [inlined]
 [12] #_sum#741
    @ ./reducedim.jl:894 [inlined]
 [13] _sum
    @ ./reducedim.jl:894 [inlined]
 [14] #_sum#740
    @ ./reducedim.jl:893 [inlined]
 [15] _sum
    @ ./reducedim.jl:893 [inlined]
 [16] #sum#738
    @ ./reducedim.jl:889 [inlined]
 [17] sum(a::Vector{Any})
    @ Base ./reducedim.jl:889
 [18] top-level scope
    @ REPL[2]:1
```

**Comment by bardo84** [comment]
With clean start, Julia 1.62 and latest JET, I get
`julia> report_file("serialize_5.jl"; concretize_patterns = [:(Writable = x_)])
[toplevel-info] virtualized the context of Main (took 0.11 sec)
[toplevel-info] entered into serialize_5.jl
[toplevel-info]  exited from serialize_5.jl (took 40.392 sec)
═════ 2 toplevel errors found ═════
┌ @ serialize_5.jl:73 
│ HINT: the following error happened mostly because of the missing concretization of global variables,
│ and this could be fixed with the `concretization_patterns` configuration.
│ Check https://aviatesk.github.io/JET.jl/dev/config/#JET.ToplevelConfig for the details.
│ ---
│ TypeError: in TypeVar, in upper bound, expected Type, got a value of type JET.AbstractGlobal    
│ Stacktrace:
│  [1] TypeVar(n::Symbol, ub::Any)
│    @ Core .\boot.jl:382
└─────────────────────
┌ @ serialize_5.jl:123 
│ HINT: the following error happened mostly because of the missing concretization of global variables,
│ and this could be fixed with the `concretization_patterns` configuration.
│ Check https://aviatesk.github.io/JET.jl/dev/config/#JET.ToplevelConfig for the details.
│ ---
│ TypeError: in TypeVar, in upper bound, expected Type, got a value of type JET.AbstractGlobal    
│ Stacktrace:
│  [1] TypeVar(n::Symbol, ub::Any)
│    @ Core .\boot.jl:382
└──────────────────────
(included_files = Set(["serialize_5.jl"]), nreported = 2)`

**Comment by aviatesk** [comment]
ops, sorry try `report_file("serialize_5.jl"; concretization_patterns = [:(Writable = x_)])`

Also, you will get much better result on v1.7 and higher.

**Comment by bardo84** [comment]
Thx, running now on 1.62!
Waiting for 1.7 final to install.
Understand that this is really work in progress, much appreciated.
