### ISSUE TITLE
Adding `println` logging to...

### ISSUE THREAD

**Issue by goerch** [aviatesk/JET.jl#282]
... `JuliaInterpreter` overloads breaks Julia when redirecting `stdout`. Is this a dangerous idea?

**Comment by aviatesk** [comment]
Could you elaborate the problem?

**Comment by goerch** [comment]
I was trying to log the interaction between `JET` and `JuliaInterpreter` and this ended in Julia crashes. In the meantime I found https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/330, so I'm not sure if something like that is a good idea?

**Comment by aviatesk** [comment]
Hm, I'm still not sure how that issue relates to debugging of JET. A reproducer is always welcome and will make discussion more concrete.

**Comment by goerch** [comment]
OK.
