### ISSUE TITLE
World age problem

### ISSUE THREAD

**Issue by goerch** [aviatesk/JET.jl#287]
When trying to find a reproducer for the world age problem reported in #225 I noticed

```
function tryeval()
      @eval newfun() = 1
      newfun()
end
tryeval()
```

results in 

```
ERROR: LoadError: MethodError: no method matching newfun()
The applicable method may be too new: running in world age 31864, while current world is 31865.
```

but JET reports

```
No errors !
```

It this expected?

**Comment by aviatesk** [comment]
We don't have any practical way to analyze `eval` expressions correctly.

So the "expected" behavior above is:
- if `newfun` is already defined in the parent scope: no error
- if `newfun` isn't defined in the parent scope: error

**Comment by goerch** [comment]
Interesting: we can't detect it, but can be hit by it. Thanks!

**Comment by aviatesk** [comment]
We do find `eval` expression, but its contents can't analyzed statically in general. So a sound analyzer should report something whenever we see `eval` expression in a local scope, but JET's default permissive analyzer will just ignore it.
