### ISSUE TITLE
false negative converting in parameterized function

### ISSUE THREAD

**Issue by dpinol** [aviatesk/JET.jl#307]
JET correctly reports in the following code that String cannot be converted to Number
```
function badTypePlain()::Number
    list=["1"]
    return list[1]
end
```

However, it doesn't for the following function passing an abstract type as argument
```
function badTypeAbstract(t::Number)::Int
    list=["1"]
    return list[1]
end
```
I guess it happens because JET does not concretize the method for all possible argument types. However, is there any way to detect it if the argument type does not impact the issue? 

thanks

**Comment by aviatesk** [comment]
`t` isn't used anywhere?

**Comment by dpinol** [comment]
It isn't, but even if it is, it still does not report any issue 
```
function badTypeAbstract(t::Number)::Int
    list=repeat(["1"], t)
    return list[1]
end

```

thanks

**Comment by aviatesk** [comment]
JET by default isn't sound and not guarantee your code _never_ sees runtime error.
You can use `mode=:sound` configuration to run JET in sound mode (but likely to be full of false positives).

If performance is what you care, use `report_opt` instead.

**Comment by dpinol** [comment]
ok, thanks. At least I see that if I do invoke the function (with a concrete type) from my package , then I do get the error, which is good enough

thanks!
