### ISSUE TITLE
false positive in type inference

### ISSUE THREAD

**Issue by jlapeyre** [aviatesk/JET.jl#313]
`@code_warn_type` shows that the method in question is inferred correctly.

I think this is wrong
```
 @ /xxx/julia_repos/EmpiricalCDFs/src/IOcdf.jl:197 Base.getproperty(info, :lowreject)
│┌ @ Base.jl:42 Base.getfield(x, f)
││ type EmpiricalCDFs.IOcdf.CDFInfo has no field lowreject
│└──────────────
```

`info` is returned by `readcdfinfo`, which returns one of two types, `CDFInfo` or `CDFHiInfo`,  or errors.

Here, `info.lowreject` is only called if the type has this field. That is, the type is `CDFHiInfo`.
```
cdf = typeof(info) == CDFInfo ?  EmpiricalCDF() : EmpiricalCDFHi(info.lowreject)
```

https://github.com/jlapeyre/EmpiricalCDFs.jl/blob/37c68e4f382486c56f67e8e1b1b4f00c907f6ed0/src/IOcdf.jl#L194-L200

The function `readcdfinfo` is here:
https://github.com/jlapeyre/EmpiricalCDFs.jl/blob/37c68e4f382486c56f67e8e1b1b4f00c907f6ed0/src/IOcdf.jl#L230-L245

**Comment by aviatesk** [comment]
`typeof(x) == T` isn't the right way
to tell the runtime type of an object to the compiler. Use `isa(x, T)` instead.
