### ISSUE TITLE
Only the last branch is checked?

### ISSUE THREAD

**Issue by Shuenhoy** [aviatesk/JET.jl#314]
```julia

a = (named = 3,)
if rand(Bool)
    print(a.notnamed)
else
    print(a.named)
end

if rand(Bool)
    print(a.named)
else
    print(a.notnamed)
end
```

For the above codes, the first `print(a.notnamed)` is always ignored, unless the condition is something trivial like `3<4` or `true`. Is this a bug? Or a limitation of the current analysis method?

**Comment by aviatesk** [comment]
It's a limitation of our current toplevel analysis. JET's toplevel analysis actually evaluates toplevel conditions in order to correctly reason about programs like:
```julia
if some_system_setting
    func(...) = ...
else
    func(...) = ...
end
```
