### ISSUE TITLE
"about" box: why "scratch"?

### ISSUE THREAD

**Issue by timholy** [aviatesk/JET.jl#316]
The "about" box on JET's ["homepage"](https://github.com/aviatesk/JET.jl) (which also shows in google search results) starts with "scratch:". Its meaning and value to the reader are unclear.

![image](https://user-images.githubusercontent.com/1525481/150674912-abd20c56-3f98-4c67-8f72-27031a4a1121.png)

**Comment by aviatesk** [comment]
I think I tried to express my humility by that word, but it seems that it may make people think JET is somewhat unreliable or unreproducible :p 

I'm fine with removing "scratch: ", or do you have any suggestion other than 

> An experimental code analyzer for Julia, no need for additional type annotations.

?

**Comment by timholy** [comment]
That would be clearer to me. I thought maybe that was an old name of the project. There's also the [Scratch language](https://scratch.mit.edu/).

**Comment by aviatesk** [comment]
Changed!
