### ISSUE TITLE
fix JET on nightly

### ISSUE THREAD

**Issue by aviatesk** [aviatesk/JET.jl#385]
[Semi-concrete IR interpreter #44803](https://github.com/JuliaLang/julia/pull/44803) brought significant changes to the Base compiler behavior, and now we need to adjust JET to it.

There is also [Refactor lattice code to expose layering and enable easy extension #46526](https://github.com/JuliaLang/julia/pull/46526), that may be causing some problem for JET (as well as gives an opportunity to improve it), but I guess the most current problems are from the semi-concrete eval change.

**Comment by quinnj** [comment]
Probably not, but in case it's helpful, here's some example failures w/ Julia nightly: https://github.com/JuliaData/Parsers.jl/actions/runs/3022413687/jobs/4861472728

**Comment by aviatesk** [comment]
Thanks. Please use JET@0.6.3 for running JET on nightly.
