### ISSUE TITLE
Failed to precompile JET

### ISSUE THREAD

**Issue by danielbrogren** [aviatesk/JET.jl#410]
From Manifest.toml
julia_version = "1.8.0"
manifest_format = "2.0"
project_hash = "fe56f39dd28204192ff84b1f022449ab67d8cfae"

[[deps.JET]]
deps = ["InteractiveUtils", "JuliaInterpreter", "LoweredCodeUtils", "MacroTools", "Pkg", "Revise", "Test"]
git-tree-sha1 = "d79a04585f9db7e3d5bbe62c7ea1b9aadaf515e4"
uuid = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
version = "0.6.14"

When doing
import Pkg; Pkg.precompile()

julia> import Pkg; Pkg.precompile()
Precompiling project...
  ✗ JET
  0 dependencies successfully precompiled in 5 seconds. 10 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

JET [c3a54625-cd67-489e-a8e7-0a5a0ff4e31b]

Failed to precompile JET [c3a54625-cd67-489e-a8e7-0a5a0ff4e31b] to /home/edanbro/.julia/compiled/v1.8/JET/jl_R3QnwD.
WARNING: could not import Compiler.CachedMethodTable into JET
ERROR: LoadError: UndefVarError: CachedMethodTable not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/JET/rofzT/src/analyzers/jetanalyzer.jl:1
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [3] include(x::String)
   @ JET ~/.julia/packages/JET/rofzT/src/JET.jl:1
 [4] top-level scope
   @ ~/.julia/packages/JET/rofzT/src/JET.jl:1540
 [5] include
   @ ./Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at /home/edanbro/.julia/packages/JET/rofzT/src/analyzers/jetanalyzer.jl:1
in expression starting at /home/edanbro/.julia/packages/JET/rofzT/src/JET.jl:1
in expression starting at stdin:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types ~/repo/bb-parent/stage/usr/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
 [2] precompile(ctx::Pkg.Types.Context, pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, already_instantiated::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API ~/repo/bb-parent/stage/usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:1427
 [3] precompile
   @ ~/repo/bb-parent/stage/usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:1058 [inlined]
 [4] #precompile#225
   @ ~/repo/bb-parent/stage/usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:1057 [inlined]
 [5] precompile (repeats 2 times)
   @ ~/repo/bb-parent/stage/usr/share/julia/stdlib/v1.8/Pkg/src/API.jl:1057 [inlined]
 [6] top-level scope
   @ REPL[4]:1

**Comment by aviatesk** [comment]
JET can be used with v1.8.2. Could you update your Julia version instead?

**Comment by danielbrogren** [comment]
Thanks.
yes, it fine now with Julia v1.8.2
