### ISSUE TITLE
report_package won't work with separate test environments

### ISSUE THREAD

**Issue by tpapp** [aviatesk/JET.jl#412]
Suppose 

1. a package `A` depends on `B`,
2. `A` has its tests in a [test-specific environment](https://pkgdocs.julialang.org/v1/creating-packages/#Test-specific-dependencies-in-Julia-1.2-and-above), which does not include explicitly include `B`

Then a call in CI like
```julia
report_package(A, target_modules=(A,))
```
will fail with the error message
```julia
JET.ActualErrorWrapped(ArgumentError("Package B not found in current path.\n- Run `import Pkg; Pkg.add(\"B\")` to install the B package."),...
```

**Comment by tpapp** [comment]
Putting `..` in `LOAD_PATH` is of course a workaround. The issue was noted in https://github.com/tpapp/DynamicHMC.jl/pull/166, but I am happy to create an MWE if necessary.

**Comment by aviatesk** [comment]
Could you try the master branch? This sort error should be fixed by #470.

**Comment by tpapp** [comment]
@aviatesk: Apologies, I missed the ping above. I checked (cf https://github.com/tpapp/DynamicHMC.jl/pull/178) and it works fine now. Thanks for fixing this.

**Comment by aviatesk** [comment]
Thanks for your cofirmation!
