### ISSUE TITLE
JETAnalyzer: false positive errors that can be analyzed to be safe by concrete evaluation

### ISSUE THREAD

**Issue by Krastanov** [aviatesk/JET.jl#444]
On Julia nightly from today:

```
v = Vector{Union{UInt8,Int,Float64}}()
push!(v, 0x0)
push!(v, 1)
push!(v, 1.0)
function f(vec)
    vectail = vec[2:end]
end
rep = @report_call f(v)
```
reports

<pre><span style="background-color:#657B83"><font color="#FDF6E3">═════ 1 possible error found ═════</font></span>
<font color="#D33682">┌ @ REPL[7]:2 </font>vec[2 : lastindex(vec)]
<font color="#D33682">│</font><font color="#268BD2">┌ @ array.jl:925 </font>copyto!(X, firstindex(X), A, first(I), lI)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">┌ @ array.jl:319 </font>Base._copyto_impl!(dest, doffs, src, soffs, n)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">┌ @ array.jl:327 </font>unsafe_copyto!(dest, doffs, src, soffs, n)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">┌ @ array.jl:281 </font>srcp = pointer(src, soffs)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">┌ @ abstractarray.jl:1243 </font>Base._memory_offset(x, i)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">┌ @ abstractarray.jl:1247 </font>Base.elsize(x)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">┌ @ abstractarray.jl:251 </font>Base.elsize(Base.typeof(A))
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">┌ @ array.jl:213 </font>Base.aligned_sizeof(T)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#CB4B16">┌ @ reflection.jl:415 </font>al = Base.datatype_alignment(T)
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#CB4B16">│ no matching method found `datatype_alignment(::Type{Union{Float64, Int64, UInt8}})`: </font><b>al = Base.datatype_alignment(T</b><font color="#93A1A1"><b>::Type{Union{Float64, Int64, UInt8}}</b></font><b>)</b>
<font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#268BD2">│</font><font color="#B58900">│</font><font color="#859900">│</font><font color="#D33682">│</font><font color="#CB4B16">└─────────────────────</font>
</pre>

Versions:

```
julia> versioninfo()
Julia Version 1.10.0-DEV.193
Commit 162ee48e1c3 (2022-12-25 12:36 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 8 × Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 4 on 8 virtual cores
```

Julia nightly installed with unreleased juliaup (patched to support nightlies)

JET version v0.6.21

Should I be reporting things like this on the JET issue tracker or on the Julia one?

**Comment by jakobnissen** [comment]
I don't think this is an issue with JET, _however_, it may provide a option for improving JET. Here is a reduced MWE:
```julia
julia> using JET

julia> f(::DataType) = false
f (generic function with 1 method)

julia> g(T::Type) = Base.isbitsunion(T) ? true : f(T)
g (generic function with 1 method)

julia> @report_call g(Union{Int, UInt})
═════ 1 possible error found ═════
┌ @ REPL[3]:1 f(T)
│ no matching method found `f(::Type{Union{Int64, UInt64}})`: f(T::Type{Union{Int64, UInt64}})
└─────────────
```
Julia is not able to statically infer that `Union{Int, UInt}` is `Base.isbitsunion` due to a `@nospecialize` in the definition of the latter. Therefore, it's not able to statically infer that a `Union` will never hit `f`.

The code in your OP example is intentionally marked as `@nospecialize`, presumably for latency reasons.
JET could avoid this false positive if it ignored `@nospecialize` - but then, this might make JET latency absolutely terrible.

**Comment by lgeissbauer-btig** [comment]
This seems simular
```
┌ @ C:\MyPkg.jl:35 result = MyPkg.DataFrame()
│┌ @ C:\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:304 DataFrames.:(var"#DataFrame#207")(pairs(NamedTuple()), #self#)
││┌ @ C:\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:306 DataFrame(Base.vect(), DataFrames.Index())
│││┌ @ C:\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:187 [quote](true, #ctor-self#, columns, colindex)
││││┌ @ C:\.julia\packages\DataFrames\dgZn3\src\dataframe\dataframe.jl:229 DataFrames.convert(Vector{AbstractVector}, columns)
│││││┌ @ array.jl:613 T(a)
││││││┌ @ array.jl:621 Base.copyto_axcheck!(Vector{AbstractVector}(Base.undef, size(x)), x)
│││││││┌ @ abstractarray.jl:1180 copyto!(dest, src)
││││││││┌ @ array.jl:339 copyto!(dest, 1, src, 1, length(src))
│││││││││┌ @ array.jl:314 Base._copyto_impl!(dest, doffs, src, soffs, n)
││││││││││┌ @ array.jl:327 unsafe_copyto!(dest, doffs, src, soffs, n)
│││││││││││┌ @ array.jl:304 Base._unsafe_copyto!(dest, doffs, src, soffs, n)
││││││││││││┌ @ array.jl:245 destp = pointer(dest, doffs)
│││││││││││││┌ @ abstractarray.jl:1243 Base._memory_offset(x, i)
││││││││││││││┌ @ abstractarray.jl:1247 Base.elsize(x)
│││││││││││││││┌ @ abstractarray.jl:251 Base.elsize(Base.typeof(A))
││││││││││││││││┌ @ array.jl:213 Base.aligned_sizeof(T)
│││││││││││││││││┌ @ reflection.jl:415 al = Base.datatype_alignment(T)
││││││││││││││││││ no matching method found `datatype_alignment(::Type{AbstractVector})`: al = Base.datatype_alignment(T::Type{AbstractVector})
```

```
│││││││││┌ @ C:\file.jl:188 requests = Base.pop!(unique_symbol_2_requests, unique_symbol, Markets._Synchronization.nothing)
││││││││││┌ @ dict.jl:620 Base._pop!(h, index)
│││││││││││┌ @ dict.jl:585 Base._delete!(h, index)
││││││││││││┌ @ dict.jl:636 Base._unsetindex!(h.keys, index)
│││││││││││││┌ @ array.jl:178 pointer(A, i)
││││││││││││││┌ @ abstractarray.jl:1243 Base._memory_offset(x, i)
│││││││││││││││┌ @ abstractarray.jl:1247 Base.elsize(x)
││││││││││││││││┌ @ abstractarray.jl:251 Base.elsize(Base.typeof(A))
│││││││││││││││││┌ @ array.jl:213 Base.aligned_sizeof(T)
││││││││││││││││││┌ @ reflection.jl:415 al = Base.datatype_alignment(T)
│││││││││││││││││││ no matching method found `datatype_alignment(::Type{SharedDataTypes.Securities.UniqueSymbol})`: al = Base.datatype_alignment(T::Type{SharedDataTypes.Securities.UniqueSymbol})
```

**Comment by jakobnissen** [comment]
This issue appears solved on Julia master and the latest version of JET:
```julia
julia> @report_call g(Union{Int, UInt})
No errors detected
```

**Comment by aviatesk** [comment]
Yeah, #529 fixed this problem. Thanks for the reminder.
