### ISSUE TITLE
Strange false positive after running `report_package`

### ISSUE THREAD

**Issue by jakobnissen** [aviatesk/JET.jl#447]
This is on Julia 1.9-beta2 using JET 0.6.21.

The issue is the following function call:
```julia
julia> foo(x::T, y::T) where {T <: Tuple{String, Int}} = isless(x, y)
foo (generic function with 1 method)

julia> y = ("a", 1);

julia> @report_call foo(y, y)
No errors detected
```

As expected. However, when first running `report_package` in a session, the exact same snippet above results in a false positive:
* Make a package with the following content:
```julia
module Foo

foo(x::T, y::T) where {T <: Tuple{String, Int}} = isless(x, y)

end # module Foo
```
* Run `report_package`:
```julia
julia> using Foo

julia> report_package(Foo)
[toplevel-info] virtualized the context of Main (took 0.013 sec)
[toplevel-info] entered into /tmp/Foo/src/Foo.jl
[toplevel-info]  exited from /tmp/Foo/src/Foo.jl (took 0.342 sec)
[toplevel-info] analyzing from top-level definitions ... 1/1
═════ 1 possible error found ═════
┌ @ /tmp/Foo/src/Foo.jl:3 Foo.isless(x, y)
│┌ @ tuple.jl:541 isless(a, b)
││ no matching method found `isless(::String, ::Int64)`, `isless(::Int64, ::String)` (2/4 union split): isless(a, b)
│└────────────────
```
* Now, running the above snippet in the REPL will also trigger the false positive:
```julia
julia> foo(x::T, y::T) where {T <: Tuple{String, Int}} = isless(x, y)
foo (generic function with 1 method)

julia> y = ("a", 1);

julia> @report_call foo(y, y)
═════ 1 possible error found ═════
┌ @ REPL[4]:1 isless(x, y)
│┌ @ tuple.jl:541 isless(a, b)
││ no matching method found `isless(::String, ::Int64)`, `isless(::Int64, ::String)` (2/4 union split): isless(a, b)
│└
```

The number of false positives in my test package is rather large - perhaps 80 or so. I'm not sure if they're all due to the bug in this issue.

**Comment by dpinol** [comment]
I can reproduce it with julia 1.8.3.

Since recent versions of JET I get a great deal of false positives, all similar to this. thanks
```
len(s::String) = length(s)
function f()
    for (i, s) in enumerate(["a"])
        len(s)
    end
end


═════ 3 possible errors found ═════
┌ @ /home/dani/source/repos/sc-engine/kk.jl:4 SCEngine.len(s)
│ no matching method found `len(::Int64)` (1/2 union split): SCEngine.len(s::Union{Int64, String})
└─────────────────────────────────────────────
┌ @ /home/dani/source/repos/sc-engine/kk.jl:5  = iterate(SCEngine.enumerate(Base.vect("a")), getfield(_2, 2))
│┌ @ iterators.jl:167 n = Base.Iterators.iterate(tuple(e.itr), rest...)
││┌ @ array.jl:898 i % Base.UInt
│││ no matching method found `rem(::String, ::Type{UInt64})`: (i::String % Base.UInt)
││└────────────────
┌ @ /home/dani/source/repos/sc-engine/kk.jl:4 SCEngine.len(s)
│ no matching method found `len(::Int64)` (1/2 union split): SCEngine.len(s::Union{Int64, String})::Any
└─────────────────────────────────────────────```

**Comment by aviatesk** [comment]
> I can reproduce it with julia 1.8.3.
> 
> Since recent versions of JET I get a great deal of false positives, all similar to this. thanks
> 
> ```
> len(s::String) = length(s)
> function f()
>     for (i, s) in enumerate(["a"])
>         len(s)
>     end
> end
> 
> 
> ═════ 3 possible errors found ═════
> ┌ @ kk.jl:4 SCEngine.len(s)
> │ no matching method found `len(::Int64)` (1/2 union split): SCEngine.len(s::Union{Int64, String})
> └─────────────────────────────────────────────
> ┌ @ kk.jl:5  = iterate(SCEngine.enumerate(Base.vect("a")), getfield(_2, 2))
> │┌ @ iterators.jl:167 n = Base.Iterators.iterate(tuple(e.itr), rest...)
> ││┌ @ array.jl:898 i % Base.UInt
> │││ no matching method found `rem(::String, ::Type{UInt64})`: (i::String % Base.UInt)
> ││└────────────────
> ┌ @ kk.jl:4 SCEngine.len(s)
> │ no matching method found `len(::Int64)` (1/2 union split): SCEngine.len(s::Union{Int64, String})::Any
> └─────────────────────────────────────────────```
> ```

Is your example really related to the `report_package` weirdness? What's the MWE?

**Comment by dpinol** [comment]
yes, I only get the false positive when the code is within a module and I call `report_package`.
The MWE is:
```
module Bar
len(s::String) = length(s)
function f()
    for (i, s) in enumerate(["a"])
        len(s)
    end
end
end

report_package(Bar)
```

What I cannot reproduce is getting the error with `@report_call` after calling `report_package`
