### ISSUE TITLE
PyCall.PyJlError has no field T

### ISSUE THREAD

**Issue by lgeissbauer-btig** [aviatesk/JET.jl#449]
```
julia> PyCall

julia> JET

julia> function f(py_object::PyCall.PyObject)
           py_object.to_eng_string()
       end
f (generic function with 1 method)

julia> JET.@report_call f(PyCall.PyObject(UInt128(1)))
═════ 1 possible error found ═════
┌ @ REPL[12]:2 py_object.to_eng_string
│┌ @ C:\.julia\packages\PyCall\9Nvls\src\PyCall.jl:318 PyCall.__getproperty(o, s)
││┌ @ C:\.julia\packages\PyCall\9Nvls\src\PyCall.jl:312 p = PyCall._getproperty(o, s)
│││┌ @ C:\.julia\packages\PyCall\9Nvls\src\PyCall.jl:303 e.T
││││┌ @ Base.jl:38 Base.getfield(x, f)
│││││ type PyCall.PyJlError has no field T
││││└──────────────

```

**Comment by aviatesk** [comment]
Is this potential error due to a bug of JET, or some type instability within PyCall.jl? If the latter, please raise an issue at their repository (Or just submit a PR to fix it).

**Comment by lgeissbauer-btig** [comment]
Oh sorry - I was not sure where to post. I think it's a problem with `PyCall`.

In general should I post these to the corresponding Pkg and only here if it's in Julia Base?

**Comment by aviatesk** [comment]
> In general should I post these to the corresponding Pkg and only here if it's in Julia Base?

Yes, this kind of issue should be posted on the target package, or JuliaLang/julia repository if the type stability lives in Base. What should be posted here are 1.) a bug within JET's analysis itself, or 2.) a suggestion of improving analysis (i.e. a request to reduce/suppress false positive)
