### ISSUE TITLE
errors on julia 1.9-rc1

### ISSUE THREAD

**Issue by daviehh** [aviatesk/JET.jl#480]
On julia Version 1.9.0-rc1, JET is unable to run: (e.g. calling `@report_opt exp(1)`)

```
ERROR: MethodError: bail_out_toplevel_call(::JET.OptAnalyzer{JET.OptAnalysisPass, typeof(JET.optanalyzer_function_filter)}, ::Core.Compiler.InferenceLoopState, ::Core.Compiler.InferenceState) is ambiguous.

Candidates:
  bail_out_toplevel_call(::Core.Compiler.AbstractInterpreter, state::Core.Compiler.InferenceLoopState, sv::Union{Core.Compiler.IRCode, Core.Compiler.InferenceState})
    @ Core.Compiler compiler/inferencestate.jl:233
  bail_out_toplevel_call(::JET.AbstractAnalyzer, sig, ::Core.Compiler.InferenceState)
    @ JET ~/.julia/packages/JET/VIRJ1/src/abstractinterpret/typeinfer.jl:685

Possible fix, define
  bail_out_toplevel_call(::JET.AbstractAnalyzer, ::Core.Compiler.InferenceLoopState, ::Core.Compiler.InferenceState)

Stacktrace:
  [1] abstract_call_gf_by_type(interp::JET.OptAnalyzer{JET.OptAnalysisPass, typeof(JET.optanalyzer_function_filter)}, f::Any, arginfo::Core.Compiler.ArgInfo, si::Core.Compiler.StmtInfo, atype::Any, sv::Core.Compiler.InferenceState, max_methods::Int64)
    @ Core.Compiler ./compiler/abstractinterpretation.jl:114

...
```

julia versioninfo

> Julia Version 1.9.0-rc1
> Commit 3b2e0d8fbc1 (2023-03-07 07:51 UTC)
> Platform Info:
>   OS: macOS (arm64-apple-darwin21.4.0)
>   CPU: 10 × Apple M1 Pro
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
>   Threads: 1 on 8 virtual cores
> Environment:
>   JULIA_MATHLINK = /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework
>   JULIA_MATHKERNEL = /Applications/Mathematica.app/Contents/MacOS/MathKernel

**Comment by daviehh** [comment]
maybe
https://github.com/aviatesk/JET.jl/blob/85a83e4c65c150eac9630262461fe30d940976e8/src/abstractinterpret/typeinfer.jl#L682
can include 1.9.0-rc1? Tested locally, with
```
@eval JET CC.bail_out_toplevel_call(::AbstractAnalyzer, ::CC.InferenceLoopState, ::InferenceState) = false
```
JET can run normally in 1.9.0-rc1

**Comment by aviatesk** [comment]
Thanks for your report. #481 should fix this issue.
