### ISSUE TITLE
Optional analyzer keyword argument gone

### ISSUE THREAD

**Issue by stemann** [aviatesk/JET.jl#494]
Did the analyzer keyword argument disappear with v0.7?

This no longer works (since v0.7.0):
```sh
julia --project=`mktemp -d` --eval '
  using Pkg
  Pkg.add(name = "JET", version = "0.7.0")
  Pkg.add("Example")
  using JET
  JET.report_package("Example"; analyzer = JET.JETAnalyzer)
'
```

Cf. https://julialang.zulipchat.com/#narrow/stream/274208-helpdesk-.28published.29/topic/JET.3A.20Specifying.20JETAnalyzer.20or.20OptAnalyzer.20option.20gone.3F

It's still in the documentation, e.g. in and around https://aviatesk.github.io/JET.jl/dev/optanalysis/#optanalysis-toplevel-entry

Best regards,
Jesper

**Comment by aviatesk** [comment]
Yeah, I removed the `analyzer` configuration in v0.7. We should remove it from the documentation. As of v0.7 and higher, the way to use `OptAnalyzer` for `report_file` etc is:
```julia
function report_file_opt(args...; jetconfigs...)
    analyzer = JET.OptAnalyzer(; jetconfigs...)
    return JET.analyze_and_report_file!(analyzer, args...; jetconfigs...)
end
```
(this should work for whatever `analyzer::AbstractAnalyzer` you define).

**Comment by stemann** [comment]
Thanks!
