### ISSUE TITLE
JET doesn't find available method?

### ISSUE THREAD

**Issue by gdalle** [aviatesk/JET.jl#539]
Hey there,
I recently tried to add `JET.test_package` to Graphs.jl, and I ran into a strange error where it refuses to find a method that does actually exist.

Versions: Julia 1.9, JET 0.8.0
Failed CI log: https://github.com/JuliaGraphs/Graphs.jl/actions/runs/5290234482/jobs/9574130454?pr=249
Where the method is: https://github.com/JuliaGraphs/Graphs.jl/blob/11f54ad59a3388a85ddfccbcb9e6791c1bebf94a/src/SimpleGraphs/SimpleGraphs.jl#L153 and https://github.com/JuliaGraphs/Graphs.jl/blob/11f54ad59a3388a85ddfccbcb9e6791c1bebf94a/src/SimpleGraphs/simplegraph.jl#L457

**Comment by aviatesk** [comment]
Thanks for your report! #540 will fix this issue.
