### ISSUE TITLE
Add a configuration to ignore the case when `x == y` return `missing`?

### ISSUE THREAD

**Issue by aviatesk** [aviatesk/JET.jl#542]
The possibility of `x == y` returning `Missing` when the types of `x` or `y` can't be precisely inferred has bothered me for a while. Ignoring this likelihood might compromise JET's accuracy and prevent it from reliably analyzing code that actually employs `missing`. So, I'm hesitant to make this the default setting - that's my stance. However, I don't wish to impose my views on others, compelling them to understand it and act on them by making unnecessary code changes or annotations. Perhaps, we could provide a configuration that allows for ignoring the possibility that `x == y` might return `missing`. Such an approach might complicate things due to the increasing number of configurations, and new issues might arise. However, having such a possibility might be better than nothing. For example, we could deactivate this configuration in interactive instances like `@report_call` or `@test_call` since the types of `x` or `y` can be easily inferred (or ought to be), and activate it in situations like in `report_package` where the types of arguments aren't specifically provided. By doing so, we can potentially allow users to be less aware of this configuration's existence.

_Originally posted by @aviatesk in https://github.com/JuliaGraphs/Graphs.jl/issues/249#issuecomment-1605290837_

**Comment by gdalle** [comment]
> Ignoring this likelihood might compromise JET's accuracy and prevent it from reliably analyzing code that actually employs missing.

I agree, it would be setting a dangerous precent. Plus I assume there are tons of other situations where a function returns what we want 99% of the time, and yet it's still good to catch the 1%

**Comment by aviatesk** [comment]
Currently, this behavior is only enabled in `report_package` and not in other scenarios. However, it might be beneficial to make it configurable, regardless of the default behavior we decide on.
