### ISSUE TITLE
Configure printing during `test_package`

### ISSUE THREAD

**Issue by gdalle** [aviatesk/JET.jl#550]
Hey there!
Now that I use JET for testing my packages, my overall happiness has increased. However, most of my test output now consists of
```
[toplevel-info] analyzing from top-level definitions (839/1681)
```
Is there a way to get rid of that?

**Comment by aviatesk** [comment]
You can give `toplevel_logger = nothing` configuration. It probably should be default for `test_package` though.

**Comment by gdalle** [comment]
Thanks!
