### ISSUE TITLE
JET gets dispatch completely wrong in this simple case, mentioning an uninvolved package

### ISSUE THREAD

**Issue by nsajko** [aviatesk/JET.jl#575]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.0-DEV.842 (2023-11-05)
 _/ |\__'_|_|_|\__'_|  |  Commit 816e31aca7d (0 days old master)
|__/                   |

julia> using JET

julia> @report_opt print("b")
═════ 2 possible errors found ═════
┌ print(xs::String) @ Base ./coreio.jl:3
│┌ print(io::Pkg.UnstableIO, arg::String) @ Pkg /cache/build/builder-amdci4-6/julialang/julia-master/usr/share/julia/stdlib/v1.11/Pkg/src/Pkg.jl:49
││ runtime dispatch detected: Pkg.print(%1::IO, arg::String)::Any
│└────────────────────
┌ print(xs::String) @ Base ./coreio.jl:3
│ runtime dispatch detected: print(%1::IO, %2::String)::Any
└────────────────────

```

1. `Pkg` is not even loaded (fresh REPL session), but JET thinks a `print` method from `Pkg` gets called from `print(xs::String) @ Base ./coreio.jl:3`
2. That method wouldn't get called even if `Pkg` *were* loaded, the call in question is `print(stdout, args...)`, no `Pkg` involvement there

I've been seeing stuff like this for a long time, usually involving the sparse arrays stdlib in reports even when it's not loaded, but this is the first short and simple example of the issue, I think.

**Comment by aviatesk** [comment]
Thanks for your feedback. Here are my insights:

1. `Pkg` is a dependency for JET, so when you `use JET`, it implicitly brings `Pkg` into scope, introducing the `print(::Pkg.UnstableIO, ::String)` method into the running session.
2. I _guess_ that `Base.stdout` wouldn't be overwritten to `Pkg.UnstableIO` instance by `Pkg.jl`. Although `Pkg.jl` has the authority to overwrite `stdout`, it's not certain, and JET cannot verify this on its own.

It's worth noting that `report_opt` is designed to report problems against code containing type instability, which includes functionality like `print` that is intentionally written in a type-unstable way. So, the behavior you're observing is kind of expected. If your code contains some parts that are inherently type-unstable, I suggest utilizing [the `function_filter` configuration](https://aviatesk.github.io/JET.jl/dev/optanalysis/#optanalysis-config).

For the first point, we might consider implementing a workaround to conceal methods derived from JET's dependencies during its analysis until users load the dependency packages by themselves.

**Comment by nsajko** [comment]
I know there's a run time dispatch here, I'm specifically complaining about JET reporting the wrong method as what would be called:

```julia-repl
julia> using Pkg

julia> @which print(stdout, "s")
print(io::IO, s::Union{SubString{String}, String})
     @ Base strings/io.jl:250
```

As you can see there's no involvement of Pkg.

**Comment by aviatesk** [comment]
My point is that `global stdout::IO` can be `UnstableIO` since `IO <: UnstableIO`.

**Comment by aviatesk** [comment]
`@which` doesn't include `print(::UnstableIO, ...)` just because `stdout` is set to the other `IO` object at the time your tried it. Pkg can always overwrite it otherwise we should declare `stdout` as constant global.

**Comment by nsajko** [comment]
Ahh, so you're saying JET doesn't know which method would get called, so it just pick the one from Pkg arbitrarily? It would be good if this arbitrariness was indicated somehow in the `@report_opt` output.

**Comment by aviatesk** [comment]
An intended interpretation of the output of `@report_opt` above would be "there are two possibly-matched methods for `print(::IO, ::String)` and it will be dynamically dispatched to either of the methods. So there is no randomness.
