### ISSUE TITLE
Tagbot isn't working

### ISSUE THREAD

**Issue by charleskawczynski** [aviatesk/JET.jl#600]
It appears from the landing page that 0.8.14 is the latest tagged release, however, https://github.com/JuliaRegistries/General/pull/99743 is the latest release.

**Comment by aviatesk** [comment]
Do you have any idea of fixing it? AFAIR the tag bot is known to be broken for long.

**Comment by aviatesk** [comment]
Now it looks like working. Thanks for your help!

**Comment by charleskawczynski** [comment]
Nice, glad I could help!
