### ISSUE TITLE
JET error `invalid lookup expr` with new `public` keyword

### ISSUE THREAD

**Issue by gdalle** [aviatesk/JET.jl#636]
`JET.test_package` throws an error on Julia 1.11 with perfectly valid uses of the new `public` keyword:

```julia
invalid lookup expr public mysymbol
```

MWE: https://github.com/gdalle/JETPublicTest.jl (check out the [CI log](https://github.com/gdalle/JETPublicTest.jl/actions/runs/9426418786/job/25969324430))

See also:

- https://github.com/JuliaLang/julia/pull/50105

**Comment by gdalle** [comment]
@aviatesk I added a very minimal MWE to the issue if you want to take a look

**Comment by aviatesk** [comment]
Thanks, JET's toplevel analysis feature currently lacks a support for the keyword. It should be feasible to implememt that though.

**Comment by gdalle** [comment]
It would be amazing, thank you!
I use `JET.test_package` in all my packages and recommend it in ModernJuliaWorkflows, but this single keyword makes all my tests fail on 1.11 and above.

**Comment by gdalle** [comment]
In the meantime, is it possible to deactivate / ignore it somehow?

**Comment by aviatesk** [comment]
No, but I'll try to implement it this weekend.

**Comment by gdalle** [comment]
Very cool, thanks. I can't overstate how useful JET is to me, so if you need a beta-tester let me know.

**Comment by gdalle** [comment]
awesome, thanks!
