### ISSUE TITLE
errors on 1.11.0-rc1

### ISSUE THREAD

**Issue by daviehh** [aviatesk/JET.jl#640]
Thanks for the package! I remembered this working on some earlier beta of 1.11.0, but with the most recent 1.11.0-rc1, it now errors on precompile:

```
julia> using JET
Precompiling JET...
Info Given JET was explicitly requested, output will be shown live
ERROR: LoadError: TypeError: in keyword argument nonoverlayed, expected UInt8, got a value of type Bool
Stacktrace:
   [1] concrete_eval_eligible
     @ ~/.julia/packages/JET/1ZQeA/src/analyzers/jetanalyzer.jl:287 [inlined]

...
```

**Comment by aviatesk** [comment]
Which version of JET are you using? JET@0.9.4 should be compatible with 1.11.

**Comment by daviehh** [comment]
Oh, tested in a new environment with JET＠0.9.4 works, looks like some SciML packages pins JET to 0.8 so it's not updated in my main environment... 

https://github.com/SciML/NonlinearSolveBase.jl/blob/9ebb92d01200fc87b07c0d895e017aa003c94a5c/Project.toml#L28

https://github.com/SciML/LinearSolve.jl/blob/11441b1ca37ca11ec946da76722c8fb5a2277ae5/Project.toml#L87

thanks a lot for the reply
