### ISSUE TITLE
OpaqueClosures

### ISSUE THREAD

**Issue by willtebbutt** [aviatesk/JET.jl#666]
Thanks for the amazing package. I make extensive use of it in several of my test suites, and have found it very useful in preventing performance bugs.

I have found a limitation related to `Core.OpaqueClosures`, which I was wondering if it might be possible to resolve. Specifically, the following works fine:
```julia
using JET

foo(x) = sin(x)
@test_opt foo(5.0) # no problems, as expected

# Build an OpaqueClosure which does exactly the same thing.
ir = Base.code_ircode_by_type(Tuple{typeof(foo), Float64})[1][1]
oc = Core.OpaqueClosure(ir; do_compile=true)
@test_opt oc(5.0) # no problems, also as expected
```
However, if we put the `OpaqueClosure` inside a callable struct, we get (what I believe to be) a false positive report of runtime dispatch:
```julia
struct Container{T}
    f::T
end

(c::Container)(x) = c.f(x)
@test_opt Container(sin)(5.0) # no problems, also as expected
@test_opt Container(oc)(5.0) # find dynamic dispatch, _not_ as expected
```

On the other hand, when JET ought to report a failure, it does not:
```julia
foo_unstable(x::Ref{Any}) = sin(x[])
ir = Base.code_ircode_by_type(Tuple{typeof(foo_unstable), Ref{Any}})[1][1];
oc = Core.OpaqueClosure(ir; do_compile=true)
@test_opt foo_unstable(Ref{Any}(5.0)) # errors, as expected
@test_opt oc(Ref{Any}(5.0)) # does not error
```
I'm not familiar with JET's internals, so I have no idea whether it ought to be able to analyse `OpaqueClosures` properly, or if that is simply not possible because we only get to access their `CodeInfo` (`Base.code_typed_opaque_closure`), not their `IRCode`.

## Additional context
I'm generating the `IRCode` to produce `OpaqueClosures` to do AD in [Mooncake.jl](https://github.com/compintell/Mooncake.jl). I am, therefore, to associated an`IRCode` to a given `OpaqueClosure`. Consequently, if it's not possible to analyse an `OpaqueClosure` for some reason, it would also be helpful if it is possible to analyse an `IRCode` on its own using JET.

## Version Information
Julia: v1.10.5
JET: v0.9.9

**Comment by aviatesk** [comment]
In general, JET (and reflection utilities like `code_typed`) doesn’t support analyzing OC. This is because the source of OC can sometimes be already inferred code, whereas inference is designed to work with non-inferred code.

Of course, it’s possible to write new routines specifically for inferred code, like in the case of `@test_opt`, but that would require adding a considerable amount of new code to JET.

**Comment by willtebbutt** [comment]
Thanks for the response and the explanation. I'll close this issue :)
